version: '3.8'


services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    hostname: backend



  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"

    depends_on:
      - backend
